DROP TABLE PUBLIC.USERS;
DROP TABLE PUBLIC.CATEGORIES;
DROP TABLE PUBLIC.LOCATIONS;
DROP TABLE PUBLIC.EVENTS;
DROP TABLE PUBLIC.REQUESTS;

-----------------------------------------------

CREATE TABLE PUBLIC.USERS
(
    ID    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    EMAIL VARCHAR(50) NOT NULL,
    NAME  VARCHAR(100) NOT NULL,
    CONSTRAINT USERS_PK
        PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC.CATEGORIES
(
    ID   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    NAME VARCHAR(50) NOT NULL,
    CONSTRAINT CATEGORIES_PK
        PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC.LOCATIONS
(
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    LAT FLOAT,
    LON FLOAT,
    CONSTRAINT LOCATIONS_PK
        PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC.EVENTS
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    annotation         VARCHAR(255),
    category_id        BIGINT,
    confirmed_requests BIGINT,
    created_on         TIMESTAMP WITHOUT TIME ZONE,
    description        VARCHAR(255),
    event_date         TIMESTAMP WITHOUT TIME ZONE,
    initiator_id       BIGINT,
    location_id        BIGINT,
    paid               BOOLEAN,
    participant_limit  INTEGER,
    published_on       TIMESTAMP WITHOUT TIME ZONE,
    request_moderation BOOLEAN,
    state              INTEGER,
    title              VARCHAR(100),
    views              BIGINT,
    CONSTRAINT events_pk
        PRIMARY KEY (id),
    CONSTRAINT EVENTS_ON_CATEGORY_fk
        FOREIGN KEY (category_id) REFERENCES public.categories (id),
    CONSTRAINT EVENTS_ON_INITIATOR_fk
        FOREIGN KEY (initiator_id) REFERENCES public.users (id),
    CONSTRAINT FK_EVENTS_ON_LOCATION
        FOREIGN KEY (location_id) REFERENCES public.locations (id)
);

CREATE TABLE PUBLIC.REQUESTS
(
    ID           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    CREATED      TIMESTAMP WITHOUT TIME ZONE,
    EVENT_ID     BIGINT,
    REQUESTER_ID BIGINT,
    STATUS       INTEGER,
    CONSTRAINT REQUEST_PK
        PRIMARY KEY (ID),
    CONSTRAINT REQUEST_ON_EVENT_FK
        FOREIGN KEY (EVENT_ID) REFERENCES PUBLIC.EVENTS (ID),
    CONSTRAINT REQUEST_ON_REQUESTER_FK
        FOREIGN KEY (REQUESTER_ID) REFERENCES PUBLIC.USERS (ID)
);

CREATE TABLE public.compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    pinned BOOLEAN  NOT NULL,
    title  VARCHAR(255) NOT NULL,
    CONSTRAINT compilations_pk
        PRIMARY KEY (id)
);

CREATE TABLE public.compilation_event
(
    compilation_id BIGINT NOT NULL,
    event_id       BIGINT NOT NULL,
    CONSTRAINT compilations_pk
        PRIMARY KEY (compilation_id, event_id),
    CONSTRAINT event_compilation_fk
        FOREIGN KEY (compilation_id) REFERENCES public.compilations (id),
    CONSTRAINT compilation_event_fk
        FOREIGN KEY (event_id) REFERENCES public.events (id)
);